import{parseRoom}from'./rooms';
import React,{useEffect,useRef,useState}from'react';import jsQR from'jsqr';import{decodeExpedition}from'./expedition';
export function CameraScanner({onRead,onClose}:{onRead:(s:string)=>void;onClose:()=>void}){
 const video=useRef<HTMLVideoElement>(null),read=useRef(onRead),close=useRef(onClose);read.current=onRead;close.current=onClose;const[status,setStatus]=useState('Opening camera…'),[failed,setFailed]=useState(false);
 useEffect(()=>{let cancelled=false,stream:MediaStream|undefined,timer:ReturnType<typeof setTimeout>|undefined;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true})!;
 const stop=()=>{cancelled=true;if(timer)clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());if(video.current)video.current.srcObject=null};
 const hide=()=>{if(document.hidden){stop();close.current()}};document.addEventListener('visibilitychange',hide);
 async function start(){try{
 if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera access is unavailable. Update Android System WebView, then reopen the app.');
 stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});
 if(cancelled){stream.getTracks().forEach(t=>t.stop());return;}const v=video.current;if(!v){stop();return;}v.srcObject=stream;await v.play();if(cancelled)return;setStatus('Point your camera at an Ore Atlas QR code.');
 function scan(){if(cancelled)return;const v=video.current;if(v&&v.readyState>=2&&v.videoWidth){const scale=Math.min(1,1200/Math.max(v.videoWidth,v.videoHeight));canvas.width=Math.round(v.videoWidth*scale);canvas.height=Math.round(v.videoHeight*scale);ctx.drawImage(v,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const qr=jsQR(pixels.data,canvas.width,canvas.height,{inversionAttempts:'attemptBoth'});if(qr){try{if(qr.data.startsWith('oreatlas://room?'))parseRoom(qr.data);else decodeExpedition(qr.data);stop();read.current(qr.data);return}catch{setStatus('That is not a valid Ore Atlas expedition QR. Try another code.')}}}timer=setTimeout(scan,160)}scan();
 }catch(e){if(cancelled)return;stop();setFailed(true);const name=(e as Error).name;setStatus(name==='NotAllowedError'?'Camera permission was denied. Enable Camera for Ore Atlas in Android app settings, then try again.':name==='NotFoundError'?'No camera was found on this device.':name==='NotReadableError'?'The camera is busy. Close other camera apps and try again.':(e as Error).message||'Could not open the camera.')}}start();return()=>{stop();document.removeEventListener('visibilitychange',hide)}},[]);
 return <section className="camera-scanner" aria-label="Live QR scanner"><div className="camera-viewport"><video ref={video} autoPlay muted playsInline aria-label="Rear camera preview"/><div className="scan-guide" aria-hidden="true"/><span className="camera-badge">LIVE QR SCANNER</span></div><p role={failed?'alert':'status'}>{status}</p><button className="crew-secondary" onClick={onClose}>{failed?'Back to expedition':'Stop camera'}</button><small>Camera frames are decoded on your phone and are not saved or uploaded.</small></section>
}
