import{LiveRoomPanel}from'./LiveRoomPanel';import{parseRoom}from'./rooms';
import{CameraScanner}from'./CameraScanner';
import React,{useEffect,useState,useRef}from'react';import QRCode from'qrcode';import jsQR from'jsqr';import{Expedition,encodeExpedition,decodeExpedition}from'./expedition';import{ores,versions}from'./atlasCatalog';
export function ExpeditionPanel({setup,incoming,onJoin,onClose}:{setup:Expedition;incoming:string;onJoin:(e:Expedition)=>void;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const[mode,setMode]=useState<'share'|'join'|'live'>(incoming?'join':'share'),[qr,setQr]=useState(''),[link,setLink]=useState(''),[text,setText]=useState(incoming),[error,setError]=useState(''),[review,setReview]=useState<Expedition|null>(null),[reading,setReading]=useState(false),[scanning,setScanning]=useState(false),[roomInvite,setRoomInvite]=useState('');
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close()},[]);
 useEffect(()=>{let active=true;try{const s=encodeExpedition(setup);setLink(s);QRCode.toDataURL(s,{width:768,margin:4,errorCorrectionLevel:'M',color:{dark:'#102018',light:'#ffffff'}}).then(v=>{if(active)setQr(v)}).catch(()=>setError('Could not create the QR code.'))}catch(e){setError((e as Error).message)}return()=>{active=false}},[setup]);
 function preview(s:string){try{if(s.trim().startsWith('oreatlas://room?')){parseRoom(s.trim());setRoomInvite(s.trim());setMode('live');setError('');return;}setReview(decodeExpedition(s));setError('')}catch(e){setReview(null);setError((e as Error).message)}}
 useEffect(()=>{if(incoming){setMode('join');setText(incoming);preview(incoming)}},[incoming]);
 async function photo(f?:File){if(!f)return;setReading(true);setError('');try{if(f.size>20000000)throw Error('Choose a QR image smaller than 20 MB.');const bitmap=await createImageBitmap(f);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=c.getContext('2d')!;ctx.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const pixels=ctx.getImageData(0,0,c.width,c.height);const result=jsQR(pixels.data,c.width,c.height,{inversionAttempts:'attemptBoth'});if(!result)throw Error('No QR found. Try a clear, straight-on screenshot.');setText(result.data);preview(result.data)}catch(e){setError((e as Error).message)}finally{setReading(false)}}
 const selectedOre=ores.find(o=>o.id===setup.oreId);
 return <dialog ref={dialog} className="expedition-dialog" onCancel={onClose} onClose={onClose}><button className="close icon-button" aria-label="Close expedition sharing" onClick={onClose}>×</button><span className="eyebrow">EXPLORE WITH FRIENDS</span><h2>Same world. Next discovery.</h2><p className="muted">Share a search setup with your mining crew.</p><div className="crew-tabs"><button className={mode==='share'?'selected':''} onClick={()=>{setScanning(false);setMode('share');setError('')}}>My QR code</button><button className={mode==='join'?'selected':''} onClick={()=>{setScanning(false);setMode('join');setError('')}}>Join expedition</button><button className={mode==='live'?'selected':''} onClick={()=>{setScanning(false);setMode('live');setError('')}}>Live room</button></div>
 <button className="crew-primary scan-qr-button" onClick={()=>{setMode('join');setError('');setReview(null);setScanning(true)}} disabled={scanning}>▣ Scan QR · Open camera</button>
 {scanning?<CameraScanner onRead={s=>{setScanning(false);setText(s);preview(s)}} onClose={()=>setScanning(false)}/>:mode==='live'?<LiveRoomPanel setup={setup} initial={roomInvite} onLoad={onJoin}/>:mode==='share'?<><div className="qr-frame">{qr?<img src={qr} alt="QR code containing your expedition setup"/>:<p>Preparing your QR…</p>}</div><div className="crew-world"><img src={`./textures/${selectedOre?.image}.png`} alt=""/><div><b>{selectedOre?.name} expedition</b><span>{setup.edition==='java'?'Java':'Bedrock'} · {versions[setup.edition].find(([v])=>v===setup.version)?.[1]} · X {setup.x} / Z {setup.z}</span></div></div><p className="crew-instructions">Your friend can tap Scan QR in Ore Atlas 5.1 and point their camera here. Sharing links and QR screenshots still works.</p><button className="crew-primary" disabled={!link} onClick={()=>window.AtlasNative.shareText(link)}>Share expedition link</button><button className="crew-secondary" disabled={!link} onClick={()=>{window.AtlasNative.copy(link);setError('Link copied. Send it to your friend.')}}>Copy link</button></>:<><label className="qr-import">{reading?'Reading QR image…':'Import a QR screenshot'}<input type="file" accept="image/*" disabled={reading} onChange={e=>photo(e.target.files?.[0])}/></label><label className="field">Or paste an expedition link<textarea value={text} onChange={e=>{setText(e.target.value);setReview(null)}} placeholder="oreatlas://expedition…" spellCheck={false}/></label><button className="crew-secondary" onClick={()=>preview(text)}>Preview expedition</button>{review&&<div className="join-preview"><span className="eyebrow">CHECK BEFORE JOINING</span><h3>{ores.find(o=>o.id===review.oreId)?.name} expedition</h3><p>{review.edition} · {versions[review.edition].find(([v])=>v===review.version)?.[1]}</p><p className="mono">Seed {review.seed}<br/>X {review.x} / Z {review.z}<br/>Y {review.minY} to {review.maxY} · {review.radius} block radius</p><button className="crew-primary" onClick={()=>onJoin(review)}>Load this expedition</button></div>}</>}
 {error&&<p className="crew-message" role="status">{error}</p>}<p className="crew-note">Setup QR codes share search settings. Live room QR codes connect friends through your configured Crew server and sync shared pins. Neither mode joins a Minecraft game server.</p></dialog>
}
