import{useSyncExternalStore}from'react';import{Expedition,validateExpedition}from'./expedition';
export type Invite={server:string;id:string;invite:string};type Pin={id:string;x:number;y:number;z:number;label:string;by:string;owner:string};type Snapshot={id:string;setup:Expedition;players:{id:string;name:string;online:boolean}[];pins:Pin[]};type State={connection:Invite&{session:string;playerId:string}|null;data:Snapshot|null;status:string;error:string};
export function serverURL(s:string){const u=new URL(s.trim());if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('Enter your server’s HTTPS address without a path.');return u.origin;}
export function roomLink(i:Invite){return'oreatlas://room?v=1&server='+encodeURIComponent(serverURL(i.server))+'&id='+i.id+'&invite='+i.invite}
export function parseRoom(s:string):Invite{if(s.length>4096)throw Error('Room link is too long.');const u=new URL(s);const id=u.searchParams.get('id')||'',invite=u.searchParams.get('invite')||'';if(u.protocol!=='oreatlas:'||u.hostname!=='room'||u.searchParams.get('v')!=='1'||! /^[\w-]{12}$/.test(id)||! /^[\w-]{32}$/.test(invite))throw Error('Invalid room invitation.');return{server:serverURL(u.searchParams.get('server')||''),id,invite};}
const listeners=new Set<()=>void>();let state:State={connection:null,data:null,status:'Not connected',error:''};let epoch=0,pollBusy=false;const emit=(v:Partial<State>)=>{state={...state,...v};listeners.forEach(f=>f())};
async function request(server:string,path:string,body:unknown,session?:string){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(server+path,{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session}:{})},body:JSON.stringify(body),signal:controller.signal,credentials:'omit',redirect:'error'});const data=await r.json();if(!r.ok)throw Error(data.error||'Server refused the request.');if(data.setup)validateExpedition(data.setup);return data}finally{clearTimeout(timer)}}
function accept(i:Invite,d:Snapshot&{session:string;playerId:string}){epoch++;const connection={...i,session:d.session,playerId:d.playerId};emit({connection,data:d,status:'Connected',error:''});window.AtlasNative.setStore('atlas-room-v1',JSON.stringify(connection));}
export const rooms={subscribe:(f:()=>void)=>{listeners.add(f);return()=>listeners.delete(f)},get:()=>state,
 async create(server:string,name:string,setup:Expedition){if(state.connection)throw Error('Leave your current room first.');server=serverURL(server);const d=await request(server,'/v1/rooms',{name,setup:validateExpedition(setup)});accept({server,id:d.id,invite:d.invite},d);return d.setup as Expedition},
 async join(i:Invite,name:string){if(state.connection)throw Error('Leave your current room first.');const d=await request(i.server,`/v1/rooms/${i.id}/join`,{invite:i.invite,name});accept(i,d);return d.setup as Expedition},
 async leave(){const c=state.connection;epoch++;emit({connection:null,data:null,status:'Not connected',error:''});window.AtlasNative.setStore('atlas-room-v1','null');if(c)try{await request(c.server,`/v1/rooms/${c.id}/leave`,{},c.session)}catch{}},
 async action(action:string,body:unknown){const c=state.connection,e=epoch;if(!c)throw Error('Join a room first.');try{const d=await request(c.server,`/v1/rooms/${c.id}/${action}`,body,c.session);if(e===epoch)emit({data:d,status:'Connected',error:''})}catch(err){if(e===epoch)emit({status:'Disconnected — retrying',error:(err as Error).message});throw err}},
 async poll(){if(pollBusy||!state.connection||document.hidden)return;pollBusy=true;try{await rooms.action('poll',{})}catch{}finally{pollBusy=false}},
 restore(){try{const c=JSON.parse(window.AtlasNative.getStore('atlas-room-v1'));if(c){parseRoom(roomLink(c));if(typeof c.session!=='string'||! /^[\w-]{32}$/.test(c.session))return;emit({connection:c,status:'Connecting…'});rooms.poll()}}catch{}}
};
export function useRoom(){return useSyncExternalStore(rooms.subscribe,rooms.get)}
export function startRooms(){rooms.restore();const timer=setInterval(()=>rooms.poll(),3000);const change=()=>{if(document.hidden&&state.connection)emit({status:'Paused in background'});else rooms.poll()};document.addEventListener('visibilitychange',change);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',change)}}
