import assert from 'node:assert/strict';import fs from'node:fs';import {fileURLToPath}from'node:url';import{moduleFor,getMap,search,checkedSeed}from'../public/engine/core.js';import{MT19937,bedrockChunk}from'../public/engine/bedrock.js';
const originalFetch=globalThis.fetch;globalThis.fetch=async u=>String(u).startsWith('file:')?new Response(fs.readFileSync(fileURLToPath(u))):originalFetch(u);
assert.throws(()=>checkedSeed('9223372036854775808'));assert.equal(checkedSeed('-9223372036854775808'),-(1n<<63n));let mt=new MT19937(5489);assert.deepEqual(Array.from({length:5},()=>mt.next()),[3499211612,581869302,3890346734,3586334585,545404204]);
const base={seed:'0',edition:'java',version:'262',dimension:0,x:0,z:0,span:600,y:64,radius:16,minY:-64,maxY:319,oreId:'diamond'};
for(const edition of ['java','bedrock']){const version=edition==='java'?'262':'2645';for(const dimension of [0,-1,1]){const q={...base,edition,version,dimension};const a=await getMap(q),b=await getMap(q);assert.equal(a.ids.length,192*192);assert.deepEqual(a.ids,b.ids);assert.ok(a.ids.every(n=>n>=0&&n<256));assert.equal(a.structures.length%3,0);console.log('map',edition,dimension,a.legend.length,'biomes')}}
for(const [i,oreId]of ['diamond','iron','gold','redstone','lapis','copper','coal','emerald','ancient_debris','nether_quartz','nether_gold'].entries()){const q={...base,oreId,dimension:i<8?0:-1};const a=await search(q);assert.ok(a.targets.every(t=>t.distance<=16&&t.y>=-64&&t.y<=319));assert.equal(new Set(a.targets.map(t=>t.id)).size,a.targets.length);console.log('Java',oreId,a.targets.length)}
for(const oreId of ['diamond','iron','gold','redstone','lapis','copper','coal','emerald']){const a=await search({...base,edition:'bedrock',version:'2645',oreId});assert.ok(a.targets.every(t=>t.distance<=16));console.log('Bedrock',oreId,a.targets.length)}
await assert.rejects(search({...base,edition:'bedrock',version:'2630'}));await assert.rejects(search({...base,dimension:1}));
const j=await moduleFor('java');const w=j._atlasCreate(121,0,262,0);assert.ok(w);assert.equal(j._atlasBiomeAt(w,0,63,0),14);j._atlasDestroy(w);
console.log('PASS: real WASM maps for both editions/all dimensions, 11 Java ore groups, 8 Bedrock groups, bounds/deduplication, seed limits, MT reference and support gates. No in-game accuracy assertion.');
