/**
 * cubiomesEngine.ts
 *
 * Loads the compiled cubiomes WASM module (see
 * native/cubiomes-shim/BUILD.md for how it's built — it does not exist
 * until that build step is run; this file will throw a clear error on
 * load if the .wasm/.mjs artifacts aren't present yet) and exposes a
 * typed, JS-friendly API over the flat C shim in shim.c.
 *
 * This is the intended production ore engine. src/engine/oregen/ (the
 * hand-written TS placement math) stays in the repo as a fallback/
 * cross-reference implementation, not the primary path — see
 * src/engine/oregen/README.md.
 */

// Generated by the emcc build (step 3 in BUILD.md) — will show a red
// squiggle / fail to resolve until that build has actually been run.
// @ts-ignore
import CubiomesModule from './cubiomes.mjs';

export interface OrePosition {
  x: number;
  y: number;
  z: number;
}

// Mirrors the `enum Ores` in cubiomes' features/ore.h — index order
// matters, it's a plain C enum. Only the ores this app currently
// exposes in its UI are listed; extend as needed, but ALWAYS keep this
// in the same order as the C header, and re-check that order any time
// cubiomes is updated.
export enum OreType {
  AndesiteOre = 0,
  BlackstoneOre,
  BuriedDiamondOre,
  BuriedLapisOre,
  ClayOre,
  CoalOre,
  CopperOre,
  DeepslateOre,
  DeltasGoldOre,
  DeltasQuartzOre,
  DiamondOre,
  DioriteOre,
  DirtOre,
  EmeraldOre,
  ExtraGoldOre,
  GoldOre,
  GraniteOre,
  GravelOre,
  InfestedOre,
  IronOre,
  LapisOre,
  LargeCopperOre,
  LargeDebrisOre,
  LargeDiamondOre,
  LowerAndesiteOre,
  LowerCoalOre,
  LowerDioriteOre,
  LowerGoldOre,
  LowerGraniteOre,
  LowerRedstoneOre,
  MagmaOre,
  MediumDiamondOre,
  MiddleIronOre,
  NetherGoldOre,
  NetherGravelOre,
  NetherQuartzOre,
  RedstoneOre,
  SmallDebrisOre,
  SmallIronOre,
  SoulSandOre,
  TuffOre,
  UpperAndesiteOre,
  UpperCoalOre,
  UpperDioriteOre,
  UpperGraniteOre,
  UpperIronOre,
}

// MCVersion ordinals are intentionally NOT hardcoded here — plain C enum
// values shift if cubiomes ever reorders/inserts entries, and getting
// this wrong silently would mean every calculation runs against the
// WRONG game version with no error. Instead, resolved at runtime from
// the shim's own accessor functions (oreEngineVersion_26_2 etc. in
// shim.c), which always reflect whatever the compiled cubiomes source
// actually defines. Call `resolveVersions()` once after module load.

const POSITIONS_PER_CHUNK_BUFFER = 512; // generous upper bound; grown automatically on overflow

/** Resolved once per loaded module from the shim's version accessors — see the note above. */
export interface ResolvedVersions {
  MC_26_1: number;
  MC_26_2: number;
}

export class CubiomesEngine {
  private module: any;
  private handle = 0;
  readonly versions: ResolvedVersions;

  private constructor(module: any) {
    this.module = module;
    this.versions = {
      MC_26_1: module.ccall('oreEngineVersion_26_1', 'number', [], []),
      MC_26_2: module.ccall('oreEngineVersion_26_2', 'number', [], []),
    };
  }

  static async create(): Promise<CubiomesEngine> {
    const module = await CubiomesModule();
    return new CubiomesEngine(module);
  }

  /**
   * Open an engine session for one world. Must call `close()` when done
   * (or open a new seed/dimension) to free the native handle.
   * Pass `engine.versions.MC_26_2` etc. for `mc` — never a raw number.
   */
  openWorld(mc: number, dimension: number, seed: bigint): void {
    if (this.handle) this.closeWorld();

    // Split into two uint32 halves — matches shim.c's oreEngineCreate
    // signature, which takes (mc, dim, seedLo, seedHi) specifically to
    // avoid passing a 64-bit value through ccall's plain 'number' type.
    const seedLo = Number(seed & 0xffffffffn);
    const seedHi = Number((seed >> 32n) & 0xffffffffn);

    this.handle = this.module.ccall(
      'oreEngineCreate',
      'number',
      ['number', 'number', 'number', 'number'],
      [mc, dimension, seedLo, seedHi]
    );

    if (!this.handle) {
      throw new Error('cubiomes: oreEngineCreate failed (out of memory?)');
    }
  }

  closeWorld(): void {
    if (this.handle) {
      this.module.ccall('oreEngineDestroy', null, ['number'], [this.handle]);
      this.handle = 0;
    }
  }

  /** Find every position of one ore type within a single chunk. */
  findOresInChunk(oreType: OreType, chunkX: number, chunkZ: number): OrePosition[] {
    if (!this.handle) throw new Error('cubiomes: call openWorld() first');

    let capacity = POSITIONS_PER_CHUNK_BUFFER;
    let result = this.tryFindOres(oreType, chunkX, chunkZ, capacity);

    // shim reports the TRUE count even if truncated — regrow and retry once.
    while (result.trueCount > capacity) {
      capacity = result.trueCount;
      result = this.tryFindOres(oreType, chunkX, chunkZ, capacity);
    }

    return result.positions;
  }

  private tryFindOres(
    oreType: OreType,
    chunkX: number,
    chunkZ: number,
    capacity: number
  ): { positions: OrePosition[]; trueCount: number } {
    const bufferPtr = this.module._malloc(capacity * 3 * 4); // 3 int32s per position

    try {
      const trueCount = this.module.ccall(
        'oreEngineFindOresInChunk',
        'number',
        ['number', 'number', 'number', 'number', 'number', 'number'],
        [this.handle, oreType, chunkX, chunkZ, bufferPtr, capacity]
      );

      if (trueCount < 0) {
        throw new Error(`cubiomes: unknown/unconfigured ore type ${oreType} for this version`);
      }

      const positions: OrePosition[] = [];
      const n = Math.min(trueCount, capacity);
      for (let i = 0; i < n; i++) {
        const x = this.module.HEAP32[bufferPtr / 4 + i * 3 + 0];
        const y = this.module.HEAP32[bufferPtr / 4 + i * 3 + 1];
        const z = this.module.HEAP32[bufferPtr / 4 + i * 3 + 2];
        positions.push({ x, y, z });
      }

      return { positions, trueCount };
    } finally {
      this.module._free(bufferPtr);
    }
  }
}
