import React,{useRef,useEffect,useImperativeHandle,forwardRef}from'react';
import{PanZoomController}from'./map/interaction/panZoomController';
import{MapState,worldToScreen,screenToWorld,clampZoom}from'./map/mapState';
import{Tile,Target,ores,structures}from'./atlasCatalog';
export type MapHandle={center:(x:number,z:number)=>void;zoom:(factor:number)=>void};
type Props={tile:Tile|null;targets:Target[];pins:Target[];selected:Target|null;grid:boolean;showStructures:boolean;onView:(v:{x:number;z:number;span:number;zoom:number})=>void;onSelect:(t:Target)=>void;onPoint:(x:number,z:number,name:string)=>void};
export const AtlasMap=forwardRef<MapHandle,Props>(function AtlasMap(props,ref){const canvas=useRef<HTMLCanvasElement>(null),wrap=useRef<HTMLDivElement>(null),p=useRef(props),tileCanvas=useRef<HTMLCanvasElement|null>(null);p.current=props;const state=useRef<MapState>({centerX:0,centerZ:0,zoom:.4,viewportWidth:500,viewportHeight:500});const hits=useRef<{x:number;y:number;t:Target;label?:string}[]>([]),drag=useRef<{x:number;y:number;moved:boolean}|null>(null),controller=useRef<PanZoomController|null>(null);
 const notify=()=>{const s=state.current;p.current.onView({x:Math.round(s.centerX),z:Math.round(s.centerZ),span:Math.max(s.viewportWidth,s.viewportHeight)/s.zoom*1.35,zoom:s.zoom})};
 const draw=()=>{const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;const s=state.current,{tile,targets,pins,selected,grid,showStructures}=p.current;ctx.fillStyle='#172b28';ctx.fillRect(0,0,s.viewportWidth,s.viewportHeight);hits.current=[];if(tile&&tileCanvas.current){const a=worldToScreen(s,{x:tile.x,z:tile.z});ctx.imageSmoothingEnabled=false;ctx.drawImage(tileCanvas.current,a.sx,a.sy,tile.n*tile.scale*s.zoom,tile.n*tile.scale*s.zoom);ctx.fillStyle='#09161928';ctx.fillRect(0,0,s.viewportWidth,s.viewportHeight)}
 const a=screenToWorld(s,{sx:0,sy:0}),b=screenToWorld(s,{sx:s.viewportWidth,sy:s.viewportHeight});let step=16;while(step*s.zoom<75)step*=4;function lines(k:number,alpha:string){ctx!.strokeStyle=alpha;ctx!.lineWidth=1;ctx!.beginPath();for(let x=Math.ceil(a.x/k)*k;x<=b.x;x+=k){let px=worldToScreen(s,{x,z:0}).sx;ctx!.moveTo(px,0);ctx!.lineTo(px,s.viewportHeight)}for(let z=Math.ceil(a.z/k)*k;z<=b.z;z+=k){let py=worldToScreen(s,{x:0,z}).sy;ctx!.moveTo(0,py);ctx!.lineTo(s.viewportWidth,py)}ctx!.stroke()}lines(step,'#d9f5e624');if(grid&&16*s.zoom>=8)lines(16,'#d9f5e640');
 if(showStructures&&tile)for(let i=0;i<tile.structures.length;i+=3){const type=tile.structures[i],x=tile.structures[i+1],z=tile.structures[i+2],{sx,sy}=worldToScreen(s,{x,z});if(sx<0||sy<0||sx>s.viewportWidth||sy>s.viewportHeight)continue;ctx.fillStyle='#172423';ctx.strokeStyle='#f3d48c';ctx.lineWidth=1.5;ctx.fillRect(sx-10,sy-10,20,20);ctx.strokeRect(sx-10,sy-10,20,20);ctx.fillStyle='#f3d48c';ctx.textAlign='center';ctx.font='bold 12px sans-serif';ctx.fillText(structures[type][0],sx,sy+4);hits.current.push({x:sx,y:sy,label:structures[type],t:{id:'structure-'+i,oreId:'structure',x,y:64,z,distance:0}})}
 for(const t of targets){const{sx,sy}=worldToScreen(s,t);if(sx<0||sy<0||sx>s.viewportWidth||sy>s.viewportHeight)continue;const is=t.id===selected?.id;ctx.fillStyle=ores.find(o=>o.id===t.oreId)?.color||'#b0f8df';ctx.fillRect(sx-(is?5:2),sy-(is?5:2),is?10:4,is?10:4);if(is){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(sx-8,sy-8,16,16)}hits.current.push({x:sx,y:sy,t})}
 for(const t of pins){const{sx,sy}=worldToScreen(s,t);ctx.strokeStyle='#ffd88e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(sx,sy,8,0,Math.PI*2);ctx.stroke();hits.current.push({x:sx,y:sy,t})}ctx.strokeStyle='#fff';ctx.lineWidth=1;const x=s.viewportWidth/2,y=s.viewportHeight/2;ctx.beginPath();ctx.moveTo(x-6,y);ctx.lineTo(x+6,y);ctx.moveTo(x,y-6);ctx.lineTo(x,y+6);ctx.stroke();};
 useEffect(()=>{const t=props.tile;if(t){const c=document.createElement('canvas');c.width=c.height=t.n;const ctx=c.getContext('2d')!,im=ctx.createImageData(t.n,t.n);for(let i=0;i<t.ids.length;i++){const color=t.palette[t.ids[i]]||0x334744;im.data[i*4]=color>>16&255;im.data[i*4+1]=color>>8&255;im.data[i*4+2]=color&255;im.data[i*4+3]=255}ctx.putImageData(im,0,0);tileCanvas.current=c}else tileCanvas.current=null;draw()},[props.tile]);
 useEffect(()=>{draw()},[props.targets,props.pins,props.selected,props.grid,props.showStructures]);
 useEffect(()=>{controller.current=new PanZoomController(()=>state.current,next=>{next.centerX=Math.max(-29900000,Math.min(29900000,next.centerX));next.centerZ=Math.max(-29900000,Math.min(29900000,next.centerZ));state.current=next;draw();notify()});const ro=new ResizeObserver(([e])=>{let{width,height}=e.contentRect;const c=canvas.current!;const d=Math.min(devicePixelRatio||1,2);c.width=width*d;c.height=height*d;c.getContext('2d')?.setTransform(d,0,0,d,0,0);state.current={...state.current,viewportWidth:width,viewportHeight:height};draw();notify()});ro.observe(wrap.current!);const c=canvas.current!;const wheel=(e:WheelEvent)=>{e.preventDefault();const r=c.getBoundingClientRect();controller.current?.onWheel(e.clientX-r.left,e.clientY-r.top,e.deltaY)};c.addEventListener('wheel',wheel,{passive:false});return()=>{ro.disconnect();c.removeEventListener('wheel',wheel)}},[]);
 useImperativeHandle(ref,()=>({center:(x,z)=>{state.current={...state.current,centerX:x,centerZ:z};draw();notify()},zoom:f=>{state.current.zoom=clampZoom(state.current.zoom*f);draw();notify()}}));
 function point(e:React.PointerEvent){const r=canvas.current!.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
 return <div className="map-canvas" ref={wrap}><canvas ref={canvas} tabIndex={0} aria-label="Biome map. Drag to pan. Use arrow keys or zoom buttons." onKeyDown={e=>{const s=state.current,step=100/s.zoom;if(e.key==='ArrowLeft')s.centerX-=step;else if(e.key==='ArrowRight')s.centerX+=step;else if(e.key==='ArrowUp')s.centerZ-=step;else if(e.key==='ArrowDown')s.centerZ+=step;else return;e.preventDefault();s.centerX=Math.max(-29900000,Math.min(29900000,s.centerX));s.centerZ=Math.max(-29900000,Math.min(29900000,s.centerZ));draw();notify()}} onPointerDown={e=>{const a=point(e);e.currentTarget.setPointerCapture(e.pointerId);if(drag.current)drag.current.moved=true;else drag.current={...a,moved:false};controller.current?.onPointerDown(e.pointerId,a.x,a.y)}} onPointerMove={e=>{const a=point(e);if(drag.current&&Math.hypot(a.x-drag.current.x,a.y-drag.current.y)>5)drag.current.moved=true;controller.current?.onPointerMove(e.pointerId,a.x,a.y)}} onPointerUp={e=>{const a=point(e);controller.current?.onPointerUp(e.pointerId,a.x,a.y);if(drag.current&&!drag.current.moved){let best=hits.current.map(h=>({...h,d:Math.hypot(h.x-a.x,h.y-a.y)})).filter(h=>h.d<14).sort((x,y)=>x.d-y.d)[0];if(best&&best.t.oreId!=='structure')p.current.onSelect(best.t);else{const w=best?best.t:screenToWorld(state.current,{sx:a.x,sy:a.y});const t=p.current.tile;let name=best?(best.label||'Structure start'):'Map position';if(t&&!best){const ix=Math.floor((w.x-t.x)/t.scale),iz=Math.floor((w.z-t.z)/t.scale);if(ix>=0&&iz>=0&&ix<t.n&&iz<t.n)name=t.legend.find(l=>l.id===t.ids[iz*t.n+ix])?.name.replace(/_/g,' ')||name}p.current.onPoint(Math.round(w.x),Math.round(w.z),name)}}drag.current=null}} onPointerCancel={e=>{controller.current?.onPointerCancel(e.pointerId);drag.current=null}}/></div>
});
